name: Build and Draft Release

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install packages for Windows
        if: runner.os == 'Windows'
        run: pip install -r requirements-windows.txt -r requirements.txt

      - name: Install packages for Mac/Linux
        if: runner.os != 'Windows'
        run: pip install -r requirements.txt

      - name: Build executables
        run: |
          pyinstaller launch.py --name myapp --icon logo.ico
          mv dist myapp

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: myapp
  draft_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Draft Release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          name: Release v1.0.0
          draft: true
          prerelease: false
