name: Build and Draft Release

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install packages for Windows
        if: runner.os == 'Windows'
        run: pip install -r requirements-windows.txt -r requirements.txt

      - name: Install packages for Mac/Linux
        if: runner.os != 'Windows'
        run: pip install -r requirements.txt

      - name: Build executables
        run: |
          pyinstaller launch.py --name myapp --icon logo.ico
          mv dist myapp

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: myapp

  draft_release:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create draft release
        id: create_draft_release
        uses: actions/create-release@v1
        with:
          tag_name: v0.1.0
          draft: true
          name: My App v0.1.0
          body: |
            This is a draft release for version 0.1.0 of My App.
            Please review and provide feedback.
          commitish: ${{ github.sha }}

      - name: Upload artifacts to draft release
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: myapp

      - name: Set output variable
        run: echo ::set-output name=draft_release_id::${{ steps.create_draft_release.outputs.id }}
